import { useStore } from "../store/useStore";
import type { Scene } from "./types";

// ─────────────────────────────────────────────────────────────────────────────
// Live bridge to the denah-mcp server. Receives scenes generated by Claude
// (via the MCP tools) and applies them; pushes the user's own edits back so the
// server stays in sync. Reconnects automatically.
// ─────────────────────────────────────────────────────────────────────────────

const WS_PORT = 5181;
const url = () => `ws://${location.hostname || "localhost"}:${WS_PORT}`;

let ws: WebSocket | null = null;
let retry = 0;
let lastJSON = ""; // last scene seen on the wire (both directions) — anti-echo
let pushTimer: ReturnType<typeof setTimeout> | undefined;

function connect() {
  try {
    ws = new WebSocket(url());
  } catch {
    scheduleReconnect();
    return;
  }

  ws.onopen = () => {
    retry = 0;
    useStore.getState().setMcpConnected(true);
    ws?.send(JSON.stringify({ type: "pull" }));
  };

  ws.onmessage = (ev) => {
    let msg: { type?: string; scene?: Scene };
    try {
      msg = JSON.parse(ev.data);
    } catch {
      return;
    }
    if (msg.type === "scene" && msg.scene) {
      const json = JSON.stringify(msg.scene);
      if (json === lastJSON) return; // nothing new / our own echo
      lastJSON = json;
      useStore.getState().applyRemote(msg.scene);
    }
  };

  ws.onclose = () => {
    useStore.getState().setMcpConnected(false);
    ws = null;
    scheduleReconnect();
  };
  ws.onerror = () => ws?.close();
}

function scheduleReconnect() {
  retry = Math.min(retry + 1, 6);
  const delay = Math.min(1000 * retry, 5000);
  setTimeout(connect, delay);
}

export function initMcpSync() {
  // The MCP bridge is a LOCAL DEV tool (the server runs alongside Claude Code on
  // localhost:5181). In a deployed/production build there is no such server, so
  // skip it entirely to avoid endless reconnect attempts + console noise.
  if (!import.meta.env.DEV) return;

  connect();

  // push local edits back to the server (debounced), skipping echoes
  useStore.subscribe((state, prev) => {
    if (state.scene === prev.scene) return;
    if (!useStore.getState().mcpConnected || !ws || ws.readyState !== WebSocket.OPEN) return;
    const json = JSON.stringify(state.scene);
    if (json === lastJSON) return; // this change came from the server
    clearTimeout(pushTimer);
    pushTimer = setTimeout(() => {
      lastJSON = json;
      ws?.send(JSON.stringify({ type: "push", scene: state.scene }));
    }, 350);
  });
}
